import 'web-animations-js';
import 'jquery';
import 'jqueryui';
import 'bootstrap';
import 'bootstrap-select';
import 'eonasdan-bootstrap-datetimepicker';
import 'bootstrap-switch';
import 'typeahead';
import 'jquery.fancytree/jquery.fancytree';